[phases.setup]
nixPkgs = ["python310", "git-lfs"]

[phases.install]
cmds = [
  "git lfs install",
  "git lfs pull",
  "ls -lh NSLC/bio_gene_expression.db || echo 'Database file not found after git lfs pull!'",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port 8000"
